"""Authentication

Revision ID: 20194658bf96
Revises: 
Create Date: 2023-04-07 22:31:07.381957

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20194658bf96'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('confirmed', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('confirmed')

    # ### end Alembic commands ###
